export const HOLIDAYS = [
  // Gazetted Holidays
  { month: 1, day: 26, name: "Republic Day" },
  { month: 3, day: 4, name: "Holi" },
  { month: 3, day: 21, name: "Id-ul-Fitr (Tentative)" },
  { month: 3, day: 26, name: "Rama Navami" },
  { month: 3, day: 31, name: "Mahavir Swami Jayanti" },
  { month: 4, day: 3, name: "Good Friday" },
  { month: 5, day: 1, name: "Buddha Purnima" },
  { month: 8, day: 15, name: "Independence Day" },
  { month: 8, day: 26, name: "Id-e-Milad" },
  { month: 10, day: 2, name: "Mahatma Gandhi's Birthday" },
  { month: 10, day: 20, name: "Dussehra (Vijayadashami)" },
  { month: 11, day: 8, name: "Diwali (Deepavali)" },
  { month: 11, day: 24, name: "Guru Nanak's Birthday" },
  { month: 12, day: 25, name: "Christmas" },

  // Regional and Religious Festivals
  { month: 1, day: 13, name: "Lohri" },
  { month: 1, day: 14, name: "Makar Sankranti / Pongal" },
  { month: 1, day: 23, name: "Vasant Panchami / Saraswati Puja" },
  { month: 2, day: 1, name: "Guru Ravidas Jayanti" },
  { month: 2, day: 15, name: "Maha Shivaratri" },
  { month: 3, day: 19, name: "Ugadi / Gudi Padwa" },
  { month: 4, day: 13, name: "Vaisakhi / Vishu / Tamil New Year" },
  { month: 6, day: 26, name: "Rath Yatra" },
  { month: 6, day: 27, name: "Rath Yatra" },
  { month: 8, day: 28, name: "Raksha Bandhan" },
  { month: 9, day: 4, name: "Janmashtami" },
  { month: 9, day: 14, name: "Ganesh Chaturthi" },
  { month: 10, day: 11, name: "Navratri" },
  { month: 10, day: 12, name: "Navratri" },
  { month: 10, day: 13, name: "Navratri" },
  { month: 10, day: 14, name: "Navratri" },
  { month: 10, day: 15, name: "Navratri" },
  { month: 10, day: 16, name: "Navratri" },
  { month: 10, day: 17, name: "Navratri" },
  { month: 10, day: 18, name: "Navratri" },
  { month: 10, day: 19, name: "Navratri" },
  { month: 11, day: 11, name: "Bhai Dooj" }
];
